apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/OsamaCodes62/devops-project-Helm.git
    targetRevision: main
    path: charts/sample-app
  destination:
    server: https://kubernetes.default.svc
    namespace: sample
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
